Dev
linkevinlin1/Insight_DE_smart_grid pull request #1
Opened 2020-06-12 21:58 UTC by linkevinlin1

First working versions of batch, stream, and producers

2020-06-13 19:05 UTC, colindiemer requested changes
Overall looks really good for this stage of the project!

Only urgent issue is to remove the hardcoded addresses and connection information.
Most of the other comments I left are generic style comments (which I wouldn't expect most people to have had time to implement at this stage in the project, so these are intended for the next few weeks). 

...combine more steps into functions, organize similar functions into files, then read those into your main files. Move hardcoded variables to config files or environment variables. These config files can also have documentation/comments to explain the variables. Scripts which actually execute should have a small `main()` instead of steps just automatically executing line by line. 

Since there are multiple scripts to be run in parallel (producer/consumer), you should consider adding a shell script to run everything automatically.

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +kafka_servers = 'b-1.kafka.0ofh61.c4.kafka.us-east-1.amazonaws.com:9092,b-2.kafka.0ofh61.c4.kafka.us-east-1.amazonaws.com:9092'
Don't hardcode addresses!  (everywhere else as well)

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +    '''
Irrelevent, but I prefer PEP style triple quotes """ instead of '''
Also, you can use type hints (https://www.python.org/dev/peps/pep-0484/) instead of having a separate @type line

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +lookbackdays = 5
parameters like these might be more appropriate to load in from a config file (.txt, JSON, whatever)

also they should have more detailed comments describing usage

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +def kafka_init(servers,topic):
You reuse kafka_init and acked in different scripts, which means they should be loaded in from a single separate file

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +        print("Failed to deliver message: %s: %s" % (str(msg), str(err)))
Replace ALL print statements with logging (https://docs.python.org/3/library/logging.html) (good in general but extra important for streaming projects)
One advantage is that logging has different "levels" so you can put error messages like this at a higher level than routine steps, or redirect low level logs to a file but print out important errors on screen.

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +while True:
The while True: steps here and elsewhere should be replaced with `if __name__ == "main"` executing a function

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +    utc_timestamp = int(time.mktime(then.timetuple())*1e3 + then.microsecond/1e3 - convert_win * 1000 / 2 + 86400 * 1000 / playback)
this should maybe be a function.

I'm wondering if you should have a separate file(s) for functions relating to time manipulations

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +        interval_list[i] = now.replace(microsecond=0).isoformat() + '/pt' + str(convert_win*2) + 's'
this line should maybe be a function

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +    df = query.export_pandas()
it seems like there should be some way to wrap up the column deletions into the query instead of exporting then removing.

2020-06-13 19:05 UTC, colindiemer commented on batch/druid_batch.py
> +        producer.produce(topic, key='key', value = value_out, callback=acked)
Instead of iterows can you use more manipulations on the dataframe first and use something like .to_json?

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +    }
good for config file

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +    Load the GREEND files into iterators.
it would be good if somewhere in the code there is documentation as to the schema of these files

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +    path = datapath+'/GREEND'
Personal preference, but I don't like hard coded path manipulations (what if I want use `/greend` instead?). e.g. you can just use datapath and a config file.

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +    house_list = [house for house in house_list if "building" in house]
Good usage of list comprehensions throughout :)

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +        filenames[hid]=iter(sorted([os.path.basename(x) for x in glob.glob(hpath+"/dataset_201*.csv")]))
If you're using a lot of filename manipulations it might make your life easier to work with something like pathlib (https://docs.python.org/3/library/pathlib.html) instead of string manipulations

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +
it might be cleaner to do these with multi-assignment, e.g. like `(x,y,z) = ["whatever"]*3`

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +
at least some of these steps need to be wrapped in functions for clarity.

One general principle is if there are multiple lines following a single `if` statement, you might consider creating a function. It's sometime much easier to read  `for i in thing: descriptive_function_name(i)` then to have the actual code block for the function there

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +    return fd, csviter
I like the concept, and I'm big on functions in general, but this seems unnecessary, and just doing `file_descriptor = open()` and `csv_iter = csv.reader()` seems fine.

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +                fileds[house_id].close()
when working with `open()` in python it is better to use it in a `with open() as file` syntax, see 7.2 of https://docs.python.org/3/tutorial/inputoutput.html. This way you don't have to worry about closing. 

(Although you may have some more subtle reason for doing it your way I missed)

2020-06-13 19:05 UTC, colindiemer commented on ingestion/producer_GREEND_batch.py
> +                pretimes[house_id] = prevalues[house_id] = None
again, try to think of how to wrap some of these steps in functions for clarity

2020-06-14 17:27 UTC, linkevinlin1 commented
How do I add more changes to this pull request?
I forgot to add Spark Structured Streaming script and I fixed some of the problems in the producers, added Airflow to control the batch processing.

2020-06-14 17:59 UTC, colindiemer commented
> How do I add more changes to this pull request?
> I forgot to add Spark Structured Streaming script and I fixed some of the problems in the producers, added Airflow to control the batch processing.
> 
> Edit: They seemed to be reflected here after I pushed them. Colin, if you got some time, please take a quick look on the streaming script. Thanks.

Yeah, PRs automatically get updated with new commits into the same branch.

I'll try to take a quick look later today or tomorrow. 😄

2020-06-14 18:02 UTC, linkevinlin1 commented
Thanks a lot! Working on scaling things up right now. I'll get to other issues you mentioned later.

2020-06-19 21:57 UTC, merged